#!/bin/sh
#
# Start rkipc
#

case "$1" in
  start)
    killall rkaiq_3A_server
    /usr/bin/RkLunch.sh &
    ;;
  stop)
    /usr/bin/RkLunch-stop.sh &
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
